<a href="https://colab.research.google.com/github/sahil-kothari/ML/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
df = pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [ ]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [ ]:
df.shape

(400, 5)

In [ ]:
df['Gender'] = df['Gender'].factorize()[0]

In [ ]:
df['Gender'] = df['Gender'].astype(int)

In [ ]:
df.dtypes

User ID            int64
Gender             int64
Age                int64
EstimatedSalary    int64
Purchased          int64
dtype: object

In [ ]:
X = df.drop(['Purchased'], axis=1).values
y = df['Purchased']

In [ ]:
X

array([[15624510,        0,       19,    19000],
       [15810944,        0,       35,    20000],
       [15668575,        1,       26,    43000],
       ...,
       [15654296,        1,       50,    20000],
       [15755018,        0,       36,    33000],
       [15594041,        1,       49,    36000]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,y, test_size=0.25, random_state=200)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, Y_train)

MultinomialNB()

In [ ]:
y_pred = nb.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1])

In [ ]:
from sklearn import metrics

In [ ]:
metrics.accuracy_score(Y_test, y_pred)*100

79.0

In [ ]:
print('Confusion Matrix')
print(metrics.confusion_matrix(Y_test, y_pred))

Confusion Matrix
[[47 13]
 [ 8 32]]


In [ ]:
nb.score(X_test, Y_test)

0.79

In [ ]:
print("1. Accuracy Score:", metrics.accuracy_score(Y_test, y_pred)*100)
print("2. Precision Score:",metrics.precision_score(Y_test, y_pred))
print("3. Recall Score:", metrics.recall_score(Y_test, y_pred))
print("4. f1 Score:", metrics.f1_score(Y_test, y_pred))

1. Accuracy Score: 79.0
2. Precision Score: 0.7111111111111111
3. Recall Score: 0.8
4. f1 Score: 0.7529411764705882
